---

- name: Install LEMP Packages
  apt:
    pkg: "{{ item }}"
    state: latest
  loop: [ 'nginx', 'mysql-server', 'python3-pymysql', 'php-fpm', 'php-mysql' ]

# Nginx Configuration

- name: Sets Nginx conf file
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ http_conf }}"

- name: Enables new site
  file:
    src: "/etc/nginx/sites-available/{{ http_conf }}"
    dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
    state: link
  notify: Reload Nginx

- name: Removes "default" site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx

# MySQL Configuration

- name: "Setting ROOT password for mysql-server"
  ignore_errors: true
  mysql_user:
    login_user: "root"
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "root"
    password: "{{ mysql_root_password }}"
    column_case_sensitive: true

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    column_case_sensitive: true

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

# UFW Configuration

- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

# Sets Up PHP Info Page

- name: Sets Up PHP Info Page
  template:
    src: "templates/info.php.j2"
    dest: "/var/www/html/info.php"