---

- name: Install php-fpm
  apt:
    pkg: "php{{ php_version }}-fpm"
    state: present

# PHP-FPM Configuration

- name: Sets php-fpm conf file
  template:
    src: "templates/www.conf.j2"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify: Restart php-fpm

- name: Create html folder
  file:
    path: /var/www/html
    state: directory
#    mode: '0755'

# Create info page

- name: Create info page
  template:
    src: "templates/info.php.j2"
    dest: "{{ www_root_path }}/info.php"
  notify: Restart php-fpm